### ISSUE TITLE
Discussion: Template repository

### ISSUE THREAD

**Issue by xzilja** [rnc-archive/template#1]
Some of you might've heard that GitHub recently released new feature for repo templates https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates

I believe this repo was initially renamed to `.github` to achieve something similar to this functionality, but it was limited to certain files?

With GitHub templates we can specify very specific project structure / add eslint configs, index.d.ts files etc... that can be used by community when bootstrapping new lib's

**Comment by mikehardy** [comment]
sweet! thanks

**Comment by mikehardy** [comment]
In response to questions above - just wanted to say that the proposed stack of eslint/typescript/detox for e2e sounds fine to me. I wish android wasn't "best effort" on detox but it seems as workable as any of the other e2e solutions

I also like 'src/' vs 'lib/' because I think of 'lib' as bundled dependencies and source, with dist/ for post-processed artifacts (if they exist), but maybe that's a dinosaur unix mindset.

**Comment by kelset** [comment]
hey @IljaDaderko are you still working on the project? If not (and btw, it's totally fine! Priorities change, so don't feel bad about it) we can "freeze" the repo until someone picks it up 🤗
